/********************************************************************************
** Form generated from reading UI file 'Window.ui'
**
** Created: Mon Jul 7 08:14:43 2014
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOW_H
#define UI_WINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QTextEdit>
#include "qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_Window
{
public:
    QGroupBox *groupBox;
    QLabel *heliPortlabel;
    QPushButton *commButton;
    QLabel *heliIPlabel;
    QLineEdit *heliIPEdit;
    QLineEdit *heliPortEdit;
    QPushButton *sendButton;
    QLabel *label;
    QPushButton *recButton;
    QLineEdit *rxPortEdit;
    QLabel *RxPortlabel;
    QLabel *label_19;
    QComboBox *rxRateChangecomboBox;
    QComboBox *txRateChangecomboBox;
    QCheckBox *AutoModecheckBox;
    QCheckBox *GPScheckBox;
    QLabel *heliIPlabel_2;
    QLineEdit *PCIPEdit;
    QGroupBox *groupBox_2;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *gyroxEdit;
    QLineEdit *gyroyEdit;
    QLineEdit *gyrozEdit;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *accelxEdit;
    QLineEdit *accelzEdit;
    QLabel *label_10;
    QLineEdit *accelyEdit;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *magxEdit;
    QLineEdit *magzEdit;
    QLabel *label_13;
    QLineEdit *magyEdit;
    QLabel *label_14;
    QLineEdit *gyroTempEdit;
    QLabel *label_15;
    QLineEdit *baroTempEdit;
    QLabel *label_16;
    QLineEdit *ultraDistEdit;
    QLabel *label_17;
    QLineEdit *pressureEdit;
    QLineEdit *voltageEdit;
    QLabel *label_18;
    QLabel *label_26;
    QLineEdit *rssiEdit;
    QLineEdit *speedEdit;
    QLabel *label_27;
    QLabel *frame_label1;
    QCheckBox *imageProcessingCheckbox;
    QGroupBox *groupBox_3;
    QTextEdit *logEdit;
    QGroupBox *groupBox_4;
    QLabel *label_20;
    QLineEdit *txEdit;
    QLineEdit *tyEdit;
    QLineEdit *tzEdit;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_21;
    QLineEdit *yawEdit;
    QLabel *roll_label;
    QLabel *yaw_label;
    QLineEdit *pitchEdit;
    QLineEdit *rollEdit;
    QLabel *pitch_label;
    QLabel *label_25;
    QCheckBox *RLED_checkbox;
    QCheckBox *GLED_checkbox;
    QCheckBox *BLED_checkbox;
    QLineEdit *vzEdit;
    QLabel *pitch_label_2;
    QLabel *yaw_label_2;
    QLineEdit *vxEdit;
    QLineEdit *vyEdit;
    QLabel *label_40;
    QLabel *roll_label_2;
    QLabel *label_41;
    QLineEdit *activeCamEdit;
    QGroupBox *groupBox_5;
    QLabel *heliIPlabel_3;
    QLineEdit *serverPortEdit;
    QPushButton *motionCaptureConnectButton;
    QLabel *heliIPlabel_4;
    QLineEdit *ips1Edit;
    QCheckBox *AutoModeCheckBoxVisual;
    QLineEdit *ips2Edit;
    QLineEdit *ips3Edit;
    QLineEdit *ips4Edit;
    QLabel *heliIPlabel_5;
    QLabel *heliIPlabel_6;
    QLabel *heliIPlabel_7;
    QPushButton *killServerConnectButton;
    QCheckBox *AutoModeCheckBoxVisual2;
    QLabel *fps_label;
    QGroupBox *groupBox_6;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *escEdit;
    QLineEdit *rightEdit;
    QLineEdit *rearEdit;
    QLineEdit *rudderEdit;
    QLineEdit *gainEdit;
    QLineEdit *leftEdit;
    QLabel *label_34;
    QLineEdit *runtimeEdit;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *collectiveEdit;
    QLineEdit *lateralEdit;
    QLineEdit *longitudinalEdit;
    QGroupBox *groupBox_7;
    QCustomPlot *qplotGraph1;
    QCustomPlot *qplotGraph2;
    QGroupBox *groupBox_8;
    QLabel *label_38;
    QLineEdit *kpEdit;
    QLabel *label_39;
    QLineEdit *lineEdit;

    void setupUi(QDialog *Window)
    {
        if (Window->objectName().isEmpty())
            Window->setObjectName(QString::fromUtf8("Window"));
        Window->resize(1249, 892);
        groupBox = new QGroupBox(Window);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 431, 201));
        groupBox->setMouseTracking(false);
        groupBox->setContextMenuPolicy(Qt::DefaultContextMenu);
        groupBox->setAutoFillBackground(false);
        groupBox->setFlat(false);
        groupBox->setCheckable(false);
        heliPortlabel = new QLabel(groupBox);
        heliPortlabel->setObjectName(QString::fromUtf8("heliPortlabel"));
        heliPortlabel->setGeometry(QRect(10, 85, 120, 17));
        commButton = new QPushButton(groupBox);
        commButton->setObjectName(QString::fromUtf8("commButton"));
        commButton->setGeometry(QRect(250, 25, 181, 55));
        heliIPlabel = new QLabel(groupBox);
        heliIPlabel->setObjectName(QString::fromUtf8("heliIPlabel"));
        heliIPlabel->setGeometry(QRect(10, 55, 120, 17));
        heliIPEdit = new QLineEdit(groupBox);
        heliIPEdit->setObjectName(QString::fromUtf8("heliIPEdit"));
        heliIPEdit->setGeometry(QRect(130, 50, 113, 27));
        heliPortEdit = new QLineEdit(groupBox);
        heliPortEdit->setObjectName(QString::fromUtf8("heliPortEdit"));
        heliPortEdit->setGeometry(QRect(130, 80, 113, 27));
        sendButton = new QPushButton(groupBox);
        sendButton->setObjectName(QString::fromUtf8("sendButton"));
        sendButton->setEnabled(false);
        sendButton->setGeometry(QRect(250, 85, 181, 25));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 145, 120, 17));
        recButton = new QPushButton(groupBox);
        recButton->setObjectName(QString::fromUtf8("recButton"));
        recButton->setEnabled(false);
        recButton->setGeometry(QRect(250, 115, 181, 25));
        rxPortEdit = new QLineEdit(groupBox);
        rxPortEdit->setObjectName(QString::fromUtf8("rxPortEdit"));
        rxPortEdit->setGeometry(QRect(130, 110, 113, 27));
        RxPortlabel = new QLabel(groupBox);
        RxPortlabel->setObjectName(QString::fromUtf8("RxPortlabel"));
        RxPortlabel->setGeometry(QRect(10, 115, 120, 17));
        label_19 = new QLabel(groupBox);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 175, 120, 17));
        rxRateChangecomboBox = new QComboBox(groupBox);
        rxRateChangecomboBox->setObjectName(QString::fromUtf8("rxRateChangecomboBox"));
        rxRateChangecomboBox->setEnabled(false);
        rxRateChangecomboBox->setGeometry(QRect(130, 170, 113, 27));
        txRateChangecomboBox = new QComboBox(groupBox);
        txRateChangecomboBox->setObjectName(QString::fromUtf8("txRateChangecomboBox"));
        txRateChangecomboBox->setEnabled(false);
        txRateChangecomboBox->setGeometry(QRect(130, 140, 113, 27));
        AutoModecheckBox = new QCheckBox(groupBox);
        AutoModecheckBox->setObjectName(QString::fromUtf8("AutoModecheckBox"));
        AutoModecheckBox->setGeometry(QRect(310, 145, 120, 22));
        QFont font;
        font.setStrikeOut(false);
        AutoModecheckBox->setFont(font);
        AutoModecheckBox->setMouseTracking(false);
        AutoModecheckBox->setLayoutDirection(Qt::RightToLeft);
        GPScheckBox = new QCheckBox(groupBox);
        GPScheckBox->setObjectName(QString::fromUtf8("GPScheckBox"));
        GPScheckBox->setGeometry(QRect(310, 175, 120, 22));
        GPScheckBox->setFont(font);
        GPScheckBox->setMouseTracking(false);
        GPScheckBox->setLayoutDirection(Qt::RightToLeft);
        heliIPlabel_2 = new QLabel(groupBox);
        heliIPlabel_2->setObjectName(QString::fromUtf8("heliIPlabel_2"));
        heliIPlabel_2->setGeometry(QRect(10, 30, 120, 17));
        PCIPEdit = new QLineEdit(groupBox);
        PCIPEdit->setObjectName(QString::fromUtf8("PCIPEdit"));
        PCIPEdit->setEnabled(true);
        PCIPEdit->setGeometry(QRect(130, 20, 113, 27));
        PCIPEdit->setReadOnly(true);
        groupBox_2 = new QGroupBox(Window);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 400, 431, 241));
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 30, 120, 17));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 60, 120, 17));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 90, 120, 17));
        gyroxEdit = new QLineEdit(groupBox_2);
        gyroxEdit->setObjectName(QString::fromUtf8("gyroxEdit"));
        gyroxEdit->setGeometry(QRect(140, 25, 80, 27));
        gyroxEdit->setReadOnly(true);
        gyroyEdit = new QLineEdit(groupBox_2);
        gyroyEdit->setObjectName(QString::fromUtf8("gyroyEdit"));
        gyroyEdit->setGeometry(QRect(240, 25, 80, 27));
        gyroyEdit->setReadOnly(true);
        gyrozEdit = new QLineEdit(groupBox_2);
        gyrozEdit->setObjectName(QString::fromUtf8("gyrozEdit"));
        gyrozEdit->setGeometry(QRect(340, 25, 80, 27));
        gyrozEdit->setReadOnly(true);
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(125, 30, 21, 17));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(225, 30, 21, 17));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(325, 30, 21, 17));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(325, 60, 21, 17));
        label_9 = new QLabel(groupBox_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(225, 60, 21, 17));
        accelxEdit = new QLineEdit(groupBox_2);
        accelxEdit->setObjectName(QString::fromUtf8("accelxEdit"));
        accelxEdit->setGeometry(QRect(140, 55, 80, 27));
        accelxEdit->setReadOnly(true);
        accelzEdit = new QLineEdit(groupBox_2);
        accelzEdit->setObjectName(QString::fromUtf8("accelzEdit"));
        accelzEdit->setGeometry(QRect(340, 55, 80, 27));
        accelzEdit->setReadOnly(true);
        label_10 = new QLabel(groupBox_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(125, 60, 21, 17));
        accelyEdit = new QLineEdit(groupBox_2);
        accelyEdit->setObjectName(QString::fromUtf8("accelyEdit"));
        accelyEdit->setGeometry(QRect(240, 55, 80, 27));
        accelyEdit->setReadOnly(true);
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(325, 90, 21, 17));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(225, 90, 21, 17));
        magxEdit = new QLineEdit(groupBox_2);
        magxEdit->setObjectName(QString::fromUtf8("magxEdit"));
        magxEdit->setGeometry(QRect(140, 85, 80, 27));
        magxEdit->setReadOnly(true);
        magzEdit = new QLineEdit(groupBox_2);
        magzEdit->setObjectName(QString::fromUtf8("magzEdit"));
        magzEdit->setGeometry(QRect(340, 85, 80, 27));
        magzEdit->setReadOnly(true);
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(125, 90, 21, 17));
        magyEdit = new QLineEdit(groupBox_2);
        magyEdit->setObjectName(QString::fromUtf8("magyEdit"));
        magyEdit->setGeometry(QRect(240, 85, 80, 27));
        magyEdit->setReadOnly(true);
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 120, 120, 17));
        gyroTempEdit = new QLineEdit(groupBox_2);
        gyroTempEdit->setObjectName(QString::fromUtf8("gyroTempEdit"));
        gyroTempEdit->setGeometry(QRect(140, 115, 80, 27));
        gyroTempEdit->setReadOnly(true);
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 150, 120, 17));
        baroTempEdit = new QLineEdit(groupBox_2);
        baroTempEdit->setObjectName(QString::fromUtf8("baroTempEdit"));
        baroTempEdit->setGeometry(QRect(140, 145, 80, 27));
        baroTempEdit->setReadOnly(true);
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 180, 120, 17));
        ultraDistEdit = new QLineEdit(groupBox_2);
        ultraDistEdit->setObjectName(QString::fromUtf8("ultraDistEdit"));
        ultraDistEdit->setGeometry(QRect(140, 175, 80, 27));
        ultraDistEdit->setReadOnly(true);
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 210, 120, 17));
        pressureEdit = new QLineEdit(groupBox_2);
        pressureEdit->setObjectName(QString::fromUtf8("pressureEdit"));
        pressureEdit->setGeometry(QRect(140, 205, 80, 27));
        pressureEdit->setReadOnly(true);
        voltageEdit = new QLineEdit(groupBox_2);
        voltageEdit->setObjectName(QString::fromUtf8("voltageEdit"));
        voltageEdit->setGeometry(QRect(340, 175, 80, 27));
        voltageEdit->setAutoFillBackground(false);
        voltageEdit->setReadOnly(true);
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(230, 180, 120, 17));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(230, 120, 120, 17));
        rssiEdit = new QLineEdit(groupBox_2);
        rssiEdit->setObjectName(QString::fromUtf8("rssiEdit"));
        rssiEdit->setGeometry(QRect(340, 115, 80, 27));
        rssiEdit->setAutoFillBackground(false);
        rssiEdit->setReadOnly(true);
        speedEdit = new QLineEdit(groupBox_2);
        speedEdit->setObjectName(QString::fromUtf8("speedEdit"));
        speedEdit->setGeometry(QRect(340, 145, 80, 27));
        speedEdit->setAutoFillBackground(false);
        speedEdit->setReadOnly(true);
        label_27 = new QLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(230, 150, 120, 17));
        frame_label1 = new QLabel(Window);
        frame_label1->setObjectName(QString::fromUtf8("frame_label1"));
        frame_label1->setGeometry(QRect(460, 70, 320, 240));
        frame_label1->setStyleSheet(QString::fromUtf8("Background-color: #000;"));
        frame_label1->setFrameShape(QFrame::Box);
        frame_label1->setAlignment(Qt::AlignCenter);
        imageProcessingCheckbox = new QCheckBox(Window);
        imageProcessingCheckbox->setObjectName(QString::fromUtf8("imageProcessingCheckbox"));
        imageProcessingCheckbox->setGeometry(QRect(580, 40, 200, 22));
        imageProcessingCheckbox->setMouseTracking(false);
        imageProcessingCheckbox->setLayoutDirection(Qt::RightToLeft);
        groupBox_3 = new QGroupBox(Window);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(460, 730, 321, 161));
        logEdit = new QTextEdit(groupBox_3);
        logEdit->setObjectName(QString::fromUtf8("logEdit"));
        logEdit->setGeometry(QRect(0, 20, 321, 131));
        logEdit->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        logEdit->setReadOnly(true);
        groupBox_4 = new QGroupBox(Window);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 640, 431, 241));
        label_20 = new QLabel(groupBox_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 30, 80, 17));
        txEdit = new QLineEdit(groupBox_4);
        txEdit->setObjectName(QString::fromUtf8("txEdit"));
        txEdit->setGeometry(QRect(140, 25, 80, 27));
        txEdit->setMouseTracking(false);
        txEdit->setReadOnly(true);
        tyEdit = new QLineEdit(groupBox_4);
        tyEdit->setObjectName(QString::fromUtf8("tyEdit"));
        tyEdit->setGeometry(QRect(240, 25, 80, 27));
        tyEdit->setMouseTracking(false);
        tyEdit->setReadOnly(true);
        tzEdit = new QLineEdit(groupBox_4);
        tzEdit->setObjectName(QString::fromUtf8("tzEdit"));
        tzEdit->setGeometry(QRect(340, 25, 80, 27));
        tzEdit->setMouseTracking(false);
        tzEdit->setReadOnly(true);
        label_22 = new QLabel(groupBox_4);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(125, 30, 21, 17));
        label_23 = new QLabel(groupBox_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(225, 30, 21, 17));
        label_24 = new QLabel(groupBox_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(325, 30, 21, 17));
        label_21 = new QLabel(groupBox_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 90, 80, 17));
        yawEdit = new QLineEdit(groupBox_4);
        yawEdit->setObjectName(QString::fromUtf8("yawEdit"));
        yawEdit->setGeometry(QRect(340, 85, 80, 27));
        yawEdit->setMouseTracking(false);
        yawEdit->setReadOnly(true);
        roll_label = new QLabel(groupBox_4);
        roll_label->setObjectName(QString::fromUtf8("roll_label"));
        roll_label->setGeometry(QRect(125, 95, 21, 17));
        yaw_label = new QLabel(groupBox_4);
        yaw_label->setObjectName(QString::fromUtf8("yaw_label"));
        yaw_label->setGeometry(QRect(325, 95, 21, 17));
        pitchEdit = new QLineEdit(groupBox_4);
        pitchEdit->setObjectName(QString::fromUtf8("pitchEdit"));
        pitchEdit->setGeometry(QRect(240, 85, 80, 27));
        pitchEdit->setMouseTracking(false);
        pitchEdit->setReadOnly(true);
        rollEdit = new QLineEdit(groupBox_4);
        rollEdit->setObjectName(QString::fromUtf8("rollEdit"));
        rollEdit->setGeometry(QRect(140, 85, 80, 27));
        rollEdit->setMouseTracking(false);
        rollEdit->setReadOnly(true);
        pitch_label = new QLabel(groupBox_4);
        pitch_label->setObjectName(QString::fromUtf8("pitch_label"));
        pitch_label->setGeometry(QRect(225, 95, 21, 17));
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 120, 80, 17));
        RLED_checkbox = new QCheckBox(groupBox_4);
        RLED_checkbox->setObjectName(QString::fromUtf8("RLED_checkbox"));
        RLED_checkbox->setGeometry(QRect(120, 120, 40, 22));
        RLED_checkbox->setLayoutDirection(Qt::RightToLeft);
        GLED_checkbox = new QCheckBox(groupBox_4);
        GLED_checkbox->setObjectName(QString::fromUtf8("GLED_checkbox"));
        GLED_checkbox->setGeometry(QRect(160, 120, 40, 22));
        GLED_checkbox->setLayoutDirection(Qt::RightToLeft);
        BLED_checkbox = new QCheckBox(groupBox_4);
        BLED_checkbox->setObjectName(QString::fromUtf8("BLED_checkbox"));
        BLED_checkbox->setGeometry(QRect(200, 120, 40, 22));
        BLED_checkbox->setLayoutDirection(Qt::RightToLeft);
        vzEdit = new QLineEdit(groupBox_4);
        vzEdit->setObjectName(QString::fromUtf8("vzEdit"));
        vzEdit->setGeometry(QRect(340, 55, 80, 27));
        vzEdit->setMouseTracking(false);
        vzEdit->setReadOnly(true);
        pitch_label_2 = new QLabel(groupBox_4);
        pitch_label_2->setObjectName(QString::fromUtf8("pitch_label_2"));
        pitch_label_2->setGeometry(QRect(225, 60, 21, 17));
        yaw_label_2 = new QLabel(groupBox_4);
        yaw_label_2->setObjectName(QString::fromUtf8("yaw_label_2"));
        yaw_label_2->setGeometry(QRect(325, 60, 21, 17));
        vxEdit = new QLineEdit(groupBox_4);
        vxEdit->setObjectName(QString::fromUtf8("vxEdit"));
        vxEdit->setGeometry(QRect(140, 55, 80, 27));
        vxEdit->setMouseTracking(false);
        vxEdit->setReadOnly(true);
        vyEdit = new QLineEdit(groupBox_4);
        vyEdit->setObjectName(QString::fromUtf8("vyEdit"));
        vyEdit->setGeometry(QRect(240, 55, 80, 27));
        vyEdit->setMouseTracking(false);
        vyEdit->setReadOnly(true);
        label_40 = new QLabel(groupBox_4);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 60, 80, 17));
        roll_label_2 = new QLabel(groupBox_4);
        roll_label_2->setObjectName(QString::fromUtf8("roll_label_2"));
        roll_label_2->setGeometry(QRect(125, 60, 21, 17));
        label_41 = new QLabel(groupBox_4);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 150, 111, 17));
        activeCamEdit = new QLineEdit(groupBox_4);
        activeCamEdit->setObjectName(QString::fromUtf8("activeCamEdit"));
        activeCamEdit->setGeometry(QRect(140, 145, 80, 27));
        activeCamEdit->setMouseTracking(false);
        activeCamEdit->setReadOnly(true);
        groupBox_5 = new QGroupBox(Window);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 220, 431, 171));
        heliIPlabel_3 = new QLabel(groupBox_5);
        heliIPlabel_3->setObjectName(QString::fromUtf8("heliIPlabel_3"));
        heliIPlabel_3->setGeometry(QRect(10, 30, 120, 17));
        serverPortEdit = new QLineEdit(groupBox_5);
        serverPortEdit->setObjectName(QString::fromUtf8("serverPortEdit"));
        serverPortEdit->setGeometry(QRect(130, 20, 113, 27));
        motionCaptureConnectButton = new QPushButton(groupBox_5);
        motionCaptureConnectButton->setObjectName(QString::fromUtf8("motionCaptureConnectButton"));
        motionCaptureConnectButton->setEnabled(true);
        motionCaptureConnectButton->setGeometry(QRect(250, 20, 181, 25));
        heliIPlabel_4 = new QLabel(groupBox_5);
        heliIPlabel_4->setObjectName(QString::fromUtf8("heliIPlabel_4"));
        heliIPlabel_4->setGeometry(QRect(10, 55, 120, 17));
        ips1Edit = new QLineEdit(groupBox_5);
        ips1Edit->setObjectName(QString::fromUtf8("ips1Edit"));
        ips1Edit->setGeometry(QRect(130, 50, 113, 27));
        AutoModeCheckBoxVisual = new QCheckBox(groupBox_5);
        AutoModeCheckBoxVisual->setObjectName(QString::fromUtf8("AutoModeCheckBoxVisual"));
        AutoModeCheckBoxVisual->setEnabled(false);
        AutoModeCheckBoxVisual->setGeometry(QRect(250, 80, 181, 22));
        ips2Edit = new QLineEdit(groupBox_5);
        ips2Edit->setObjectName(QString::fromUtf8("ips2Edit"));
        ips2Edit->setGeometry(QRect(130, 80, 113, 27));
        ips3Edit = new QLineEdit(groupBox_5);
        ips3Edit->setObjectName(QString::fromUtf8("ips3Edit"));
        ips3Edit->setGeometry(QRect(130, 110, 113, 27));
        ips4Edit = new QLineEdit(groupBox_5);
        ips4Edit->setObjectName(QString::fromUtf8("ips4Edit"));
        ips4Edit->setGeometry(QRect(130, 140, 113, 27));
        heliIPlabel_5 = new QLabel(groupBox_5);
        heliIPlabel_5->setObjectName(QString::fromUtf8("heliIPlabel_5"));
        heliIPlabel_5->setGeometry(QRect(10, 85, 120, 17));
        heliIPlabel_6 = new QLabel(groupBox_5);
        heliIPlabel_6->setObjectName(QString::fromUtf8("heliIPlabel_6"));
        heliIPlabel_6->setGeometry(QRect(10, 115, 120, 17));
        heliIPlabel_7 = new QLabel(groupBox_5);
        heliIPlabel_7->setObjectName(QString::fromUtf8("heliIPlabel_7"));
        heliIPlabel_7->setGeometry(QRect(10, 145, 120, 17));
        killServerConnectButton = new QPushButton(groupBox_5);
        killServerConnectButton->setObjectName(QString::fromUtf8("killServerConnectButton"));
        killServerConnectButton->setEnabled(false);
        killServerConnectButton->setGeometry(QRect(250, 50, 181, 25));
        AutoModeCheckBoxVisual2 = new QCheckBox(groupBox_5);
        AutoModeCheckBoxVisual2->setObjectName(QString::fromUtf8("AutoModeCheckBoxVisual2"));
        AutoModeCheckBoxVisual2->setEnabled(false);
        AutoModeCheckBoxVisual2->setGeometry(QRect(250, 110, 181, 22));
        fps_label = new QLabel(groupBox_5);
        fps_label->setObjectName(QString::fromUtf8("fps_label"));
        fps_label->setGeometry(QRect(250, 140, 120, 17));
        groupBox_6 = new QGroupBox(Window);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(460, 400, 321, 231));
        label_28 = new QLabel(groupBox_6);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 30, 70, 17));
        label_29 = new QLabel(groupBox_6);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 60, 70, 17));
        label_30 = new QLabel(groupBox_6);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 90, 70, 17));
        label_31 = new QLabel(groupBox_6);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 120, 70, 17));
        label_32 = new QLabel(groupBox_6);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 150, 70, 17));
        label_33 = new QLabel(groupBox_6);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 180, 70, 17));
        escEdit = new QLineEdit(groupBox_6);
        escEdit->setObjectName(QString::fromUtf8("escEdit"));
        escEdit->setGeometry(QRect(90, 25, 80, 27));
        escEdit->setReadOnly(true);
        rightEdit = new QLineEdit(groupBox_6);
        rightEdit->setObjectName(QString::fromUtf8("rightEdit"));
        rightEdit->setGeometry(QRect(90, 55, 80, 27));
        rightEdit->setReadOnly(true);
        rearEdit = new QLineEdit(groupBox_6);
        rearEdit->setObjectName(QString::fromUtf8("rearEdit"));
        rearEdit->setGeometry(QRect(90, 85, 80, 27));
        rearEdit->setReadOnly(true);
        rudderEdit = new QLineEdit(groupBox_6);
        rudderEdit->setObjectName(QString::fromUtf8("rudderEdit"));
        rudderEdit->setGeometry(QRect(90, 115, 80, 27));
        rudderEdit->setReadOnly(true);
        gainEdit = new QLineEdit(groupBox_6);
        gainEdit->setObjectName(QString::fromUtf8("gainEdit"));
        gainEdit->setGeometry(QRect(90, 145, 80, 27));
        gainEdit->setReadOnly(true);
        leftEdit = new QLineEdit(groupBox_6);
        leftEdit->setObjectName(QString::fromUtf8("leftEdit"));
        leftEdit->setGeometry(QRect(90, 175, 80, 27));
        leftEdit->setReadOnly(true);
        label_34 = new QLabel(groupBox_6);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 210, 70, 17));
        runtimeEdit = new QLineEdit(groupBox_6);
        runtimeEdit->setObjectName(QString::fromUtf8("runtimeEdit"));
        runtimeEdit->setGeometry(QRect(90, 205, 80, 27));
        runtimeEdit->setReadOnly(true);
        label_35 = new QLabel(groupBox_6);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(180, 30, 70, 17));
        label_36 = new QLabel(groupBox_6);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(180, 60, 70, 17));
        label_37 = new QLabel(groupBox_6);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(180, 90, 70, 17));
        collectiveEdit = new QLineEdit(groupBox_6);
        collectiveEdit->setObjectName(QString::fromUtf8("collectiveEdit"));
        collectiveEdit->setGeometry(QRect(240, 25, 80, 27));
        collectiveEdit->setReadOnly(true);
        lateralEdit = new QLineEdit(groupBox_6);
        lateralEdit->setObjectName(QString::fromUtf8("lateralEdit"));
        lateralEdit->setGeometry(QRect(240, 55, 80, 27));
        lateralEdit->setReadOnly(true);
        longitudinalEdit = new QLineEdit(groupBox_6);
        longitudinalEdit->setObjectName(QString::fromUtf8("longitudinalEdit"));
        longitudinalEdit->setGeometry(QRect(240, 85, 80, 27));
        longitudinalEdit->setReadOnly(true);
        groupBox_7 = new QGroupBox(Window);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(790, 10, 451, 871));
        qplotGraph1 = new QCustomPlot(groupBox_7);
        qplotGraph1->setObjectName(QString::fromUtf8("qplotGraph1"));
        qplotGraph1->setGeometry(QRect(10, 30, 430, 400));
        qplotGraph2 = new QCustomPlot(groupBox_7);
        qplotGraph2->setObjectName(QString::fromUtf8("qplotGraph2"));
        qplotGraph2->setGeometry(QRect(10, 450, 430, 400));
        groupBox_8 = new QGroupBox(Window);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(460, 640, 331, 91));
        label_38 = new QLabel(groupBox_8);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 30, 70, 17));
        kpEdit = new QLineEdit(groupBox_8);
        kpEdit->setObjectName(QString::fromUtf8("kpEdit"));
        kpEdit->setGeometry(QRect(90, 25, 80, 27));
        kpEdit->setReadOnly(true);
        label_39 = new QLabel(groupBox_8);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(180, 30, 70, 17));
        lineEdit = new QLineEdit(groupBox_8);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(240, 25, 80, 27));
        lineEdit->setReadOnly(true);

        retranslateUi(Window);

        QMetaObject::connectSlotsByName(Window);
    } // setupUi

    void retranslateUi(QDialog *Window)
    {
        Window->setWindowTitle(QApplication::translate("Window", "Window", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("Window", "Helicopter Communication", 0, QApplication::UnicodeUTF8));
        heliPortlabel->setText(QApplication::translate("Window", "Helicopter Port", 0, QApplication::UnicodeUTF8));
        commButton->setText(QApplication::translate("Window", "Connect", 0, QApplication::UnicodeUTF8));
        heliIPlabel->setText(QApplication::translate("Window", "Helicopter IP", 0, QApplication::UnicodeUTF8));
        heliIPEdit->setText(QApplication::translate("Window", "192.168.1.104", 0, QApplication::UnicodeUTF8));
        heliPortEdit->setText(QApplication::translate("Window", "2002", 0, QApplication::UnicodeUTF8));
        sendButton->setText(QApplication::translate("Window", "Send", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Window", "Tx Rate (Hz)", 0, QApplication::UnicodeUTF8));
        recButton->setText(QApplication::translate("Window", "Receive", 0, QApplication::UnicodeUTF8));
        rxPortEdit->setText(QApplication::translate("Window", "2002", 0, QApplication::UnicodeUTF8));
        RxPortlabel->setText(QApplication::translate("Window", "Rx Port", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("Window", "Tx Rate Heli (Hz)", 0, QApplication::UnicodeUTF8));
        rxRateChangecomboBox->clear();
        rxRateChangecomboBox->insertItems(0, QStringList()
         << QApplication::translate("Window", "OFF", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "10", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "20", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "33", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "50", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "100", 0, QApplication::UnicodeUTF8)
        );
        txRateChangecomboBox->clear();
        txRateChangecomboBox->insertItems(0, QStringList()
         << QApplication::translate("Window", "5", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "10", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "20", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "33", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "50", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("Window", "100", 0, QApplication::UnicodeUTF8)
        );
        AutoModecheckBox->setText(QApplication::translate("Window", "Auto Mode", 0, QApplication::UnicodeUTF8));
        GPScheckBox->setText(QApplication::translate("Window", "GPS Mode", 0, QApplication::UnicodeUTF8));
        heliIPlabel_2->setText(QApplication::translate("Window", "Computer IP", 0, QApplication::UnicodeUTF8));
        PCIPEdit->setText(QApplication::translate("Window", "137.158.130.83", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("Window", "Data", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Window", "Gyroscope", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("Window", "Accelerometer", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Window", "Magnetometer", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Window", "x:", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Window", "y:", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Window", "z:", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Window", "z:", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Window", "y:", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Window", "x:", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Window", "z:", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Window", "y:", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("Window", "x:", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Window", "Gyro Temp degC", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Window", "Baro Temp degC", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Window", "Ultra dist. (cm)", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Window", "Pressure (Pa)", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Window", "Voltage (V)", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("Window", "RSSI (dBm)", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("Window", "Speed (rpm)", 0, QApplication::UnicodeUTF8));
        frame_label1->setText(QApplication::translate("Window", "Camera 1", 0, QApplication::UnicodeUTF8));
        imageProcessingCheckbox->setText(QApplication::translate("Window", "Enable Image Processing", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("Window", "Log", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("Window", "Estimation", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Window", "Translation", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Window", "x:", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("Window", "y:", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("Window", "z:", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Window", "Rotation", 0, QApplication::UnicodeUTF8));
        roll_label->setText(QApplication::translate("Window", "R:", 0, QApplication::UnicodeUTF8));
        yaw_label->setText(QApplication::translate("Window", "Y:", 0, QApplication::UnicodeUTF8));
        pitch_label->setText(QApplication::translate("Window", "P:", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("Window", "LED Control", 0, QApplication::UnicodeUTF8));
        RLED_checkbox->setText(QApplication::translate("Window", "R", 0, QApplication::UnicodeUTF8));
        GLED_checkbox->setText(QApplication::translate("Window", "G", 0, QApplication::UnicodeUTF8));
        BLED_checkbox->setText(QApplication::translate("Window", "B", 0, QApplication::UnicodeUTF8));
        pitch_label_2->setText(QApplication::translate("Window", "y:", 0, QApplication::UnicodeUTF8));
        yaw_label_2->setText(QApplication::translate("Window", "z:", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("Window", "Velocity", 0, QApplication::UnicodeUTF8));
        roll_label_2->setText(QApplication::translate("Window", "x:", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("Window", "Active Cameras", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("Window", "Motion Capture Communication", 0, QApplication::UnicodeUTF8));
        heliIPlabel_3->setText(QApplication::translate("Window", "Server Port", 0, QApplication::UnicodeUTF8));
        serverPortEdit->setText(QApplication::translate("Window", "2010", 0, QApplication::UnicodeUTF8));
        motionCaptureConnectButton->setText(QApplication::translate("Window", "Connect", 0, QApplication::UnicodeUTF8));
        heliIPlabel_4->setText(QApplication::translate("Window", "IP Camera 1", 0, QApplication::UnicodeUTF8));
        ips1Edit->setText(QApplication::translate("Window", "192.168.1.100", 0, QApplication::UnicodeUTF8));
        AutoModeCheckBoxVisual->setText(QApplication::translate("Window", "Auto-mode", 0, QApplication::UnicodeUTF8));
        ips2Edit->setText(QApplication::translate("Window", "192.168.1.101", 0, QApplication::UnicodeUTF8));
        ips3Edit->setText(QApplication::translate("Window", "192.168.1.102", 0, QApplication::UnicodeUTF8));
        ips4Edit->setText(QApplication::translate("Window", "127.0.0.1", 0, QApplication::UnicodeUTF8));
        heliIPlabel_5->setText(QApplication::translate("Window", "IP Camera 2", 0, QApplication::UnicodeUTF8));
        heliIPlabel_6->setText(QApplication::translate("Window", "IP Camera 3", 0, QApplication::UnicodeUTF8));
        heliIPlabel_7->setText(QApplication::translate("Window", "IP Camera 4", 0, QApplication::UnicodeUTF8));
        killServerConnectButton->setText(QApplication::translate("Window", "Kill Server", 0, QApplication::UnicodeUTF8));
        AutoModeCheckBoxVisual2->setText(QApplication::translate("Window", "Sync-sample fixed", 0, QApplication::UnicodeUTF8));
        fps_label->setText(QApplication::translate("Window", "FPS: 0", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("Window", "Servo Inputs", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("Window", "ESC", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("Window", "Right", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("Window", "Rear", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("Window", "Rudder", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("Window", "Gain", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("Window", "Left", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("Window", "Run (ms)", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("Window", "Col.", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("Window", "A Lat.", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("Window", "B Lon.", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("Window", "Real-Time Plots", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("Window", "Speed Control Parameters", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("Window", "Kp", 0, QApplication::UnicodeUTF8));
        kpEdit->setText(QApplication::translate("Window", "0", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("Window", "Ki", 0, QApplication::UnicodeUTF8));
        lineEdit->setText(QApplication::translate("Window", "0", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Window: public Ui_Window {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOW_H
